# -*- mode: Yaml; -*-
# vi: set ts=2 sw=2 sts=0 et:

---
- hosts: guests:extras
  gather_facts: no
  become: yes
  tasks:
    - name: Disable SELinux
      selinux:
        state: disabled

    - name: Upgrade all Packages
      yum:
        name: "*"
        state: latest

    - name: Install Dependencies
      yum:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - curl
          - bzip2
          - git
          - gcc
          - patch
          - autoconf
          - automake
          - bison
          - openssl-devel
          - libyaml-devel
          - readline-devel
          - zlib-devel
