# -*- mode: Yaml; -*-
# vi: set ts=2 sw=2 sts=0 et:

---
- hosts: guests:extras
  become: yes
  gather_facts: no
  tasks:
    - name: Add nginx repository
      yum_repository:
        name: nginx
        description: nginx repository
        baseurl: http://nginx.org/packages/centos/7/$basearch/
        gpgcheck: no
        enabled: yes
    - name: Install nginx
      yum:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - nginx
    - name: start nginx
      systemd:
        name: nginx
        state: started
        daemon_reload: yes
        enabled: yes
    - name: clean nginx
      file:
        path: /etc/nginx/conf.d/default.conf
        state: absent
      notify:
        - reload nginx
    - name: Copy isucon nginx config
      copy:
        src: ../files/etc/nginx/conf.d/{{ item }}
        dest: /etc/nginx/conf.d/{{ item }}
        owner: root
        group: root
        mode: 0644
      with_items:
        - isucon.conf
       #- isucon-php.conf
      notify:
        - reload nginx
  handlers:
    - name: reload nginx
      systemd:
        name: nginx
        state: reloaded
        daemon_reload: yes

