# -*- mode: Yaml; -*-
# vi: set ts=2 sw=2 sts=0 et:

---
- hosts: guests:extras
#- hosts: extras
  become: yes
  become_user: isucon
  gather_facts: no
  tasks:
    - name: mkdir backup
      file:
        path: /home/isucon/backup/
        state: directory

    - name: mkdir repos
      file:
        path: /home/isucon/repos/
        state: directory

    - name: clean private_isu.git
      file:
        path: /home/isucon/repos/private_isu.git
        state: absent

    - name: clone repos
      git:
        #repo: https://github.com/catatsuy/private-isu.git
        repo: https://github.com/tyabu12/private-isu.git
        dest: /home/isucon/repos/private_isu.git
        version: master

    - name: clean unnecessary directories
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /home/isucon/repos/private_isu.git/.git
        - /home/isucon/repos/private_isu.git/ansible
        - /home/isucon/repos/private_isu.git/benchmarker
        - /home/isucon/repos/private_isu.git/e2etest
        - /home/isucon/repos/private_isu.git/portal
        - /home/isucon/repos/private_isu.git/provisioning
        - /home/isucon/repos/private_isu.git/README.md

    - name: git init
      shell: >
        cd /home/isucon/repos/private_isu.git/
        && git init
        && git add .
        && git config --global user.email 'test@example.com'
        && git config --global user.name 'admin'
        && git commit -m 'Initial commit'

    - name: create working copy
      git:
        repo: file:///home/isucon/repos/private_isu.git
        dest: /home/isucon/private_isu
        version: master
        update: yes
        force: yes

