- hosts: guests:extras
  become: yes
  tasks:
    - name: Setup env.sh file
      copy:
        src: ../files/home/isucon/env.sh
        dest: /home/isucon/env.sh
        owner: isucon
        group: isucon
        mode: 0644
#- hosts: guests:extras
#- hosts: extras
# become: yes
# become_user: isucon
# gather_facts: no
# tasks:
#   - name: bundle install
#     shell: cd /home/isucon/private_isu/webapp/ruby; bash -lc "bundle install"

- hosts: guests:extras
#- hosts: extras
  become: yes
  become_user: isucon
  gather_facts: no
  tasks:
    - name: go build
      shell: bash -lc "./setup.sh"
      args:
        chdir: /home/isucon/private_isu/webapp/golang

#- hosts: guests:extras
#  become: yes
#  become_user: isucon
#  gather_facts: no
#  tasks:
#    - name: download composer.phar
#      get_url: url=http://getcomposer.org/composer.phar dest=/home/isucon/private_isu/webapp/php/composer.phar force=1 mode=755
#    - name: composer install
#      shell: cd /home/isucon/private_isu/webapp/php; bash -lc "./composer.phar install"

#- hosts: guests:extras
#  become: yes
#  become_user: isucon
#  gather_facts: no
#  tasks:
#    - name: npm install
#      shell: cd /home/isucon/private_isu/webapp/node; bash -lc "npm install"

- hosts: guests:extras
  become: yes
  tasks:
#    - name: ruby (systemd)
#      copy: src=../files/etc/systemd/system/isu-ruby.service dest=/etc/systemd/system/isu-ruby.service owner=root mode=0644
    - name: go app (systemd)
      copy:
        src: ../files/etc/systemd/system/isu-go.service
        dest: /etc/systemd/system/isu-go.service
        owner: root
        group: root
        mode: 0644
#    - name: node app (systemd)
#      copy: src=../files/etc/systemd/system/isu-node.service dest=/etc/systemd/system/isu-node.service owner=root mode=0644
    - name: default application selection
      systemd:
        name: isu-go
        state: started
        daemon_reload: yes
        enabled: true
